using System;
using System.Collections.Generic;
using System.Text;
using System.Windows.Input;

namespace CommonLib
{
    public class Arduino
    {
        public static byte MSG_KEY = 1;
        public static byte MSG_MOUSE = 2;

        public static byte KEY_NONE = 0;

        public static byte KEY_CTRL = 0x01;
        public static byte KEY_SHIFT = 0x02;
        public static byte KEY_ALT = 0x04;
        public static byte KEY_GUI = 0x08;
        public static byte KEY_LEFT_CTRL = 0x01;
        public static byte KEY_LEFT_SHIFT = 0x02;
        public static byte KEY_LEFT_ALT = 0x04;
        public static byte KEY_LEFT_GUI = 0x08;
        public static byte KEY_RIGHT_CTRL = 0x10;
        public static byte KEY_RIGHT_SHIFT = 0x20;
        public static byte KEY_RIGHT_ALT = 0x40;
        public static byte KEY_RIGHT_GUI = 0x80;

        public static byte KEY_A = 4;
        public static byte KEY_B = 5;
        public static byte KEY_C = 6;
        public static byte KEY_D = 7;
        public static byte KEY_E = 8;
        public static byte KEY_F = 9;
        public static byte KEY_G = 10;
        public static byte KEY_H = 11;
        public static byte KEY_I = 12;
        public static byte KEY_J = 13;
        public static byte KEY_K = 14;
        public static byte KEY_L = 15;
        public static byte KEY_M = 16;
        public static byte KEY_N = 17;
        public static byte KEY_O = 18;
        public static byte KEY_P = 19;
        public static byte KEY_Q = 20;
        public static byte KEY_R = 21;
        public static byte KEY_S = 22;
        public static byte KEY_T = 23;
        public static byte KEY_U = 24;
        public static byte KEY_V = 25;
        public static byte KEY_W = 26;
        public static byte KEY_X = 27;
        public static byte KEY_Y = 28;
        public static byte KEY_Z = 29;
        public static byte KEY_1 = 30;
        public static byte KEY_2 = 31;
        public static byte KEY_3 = 32;
        public static byte KEY_4 = 33;
        public static byte KEY_5 = 34;
        public static byte KEY_6 = 35;
        public static byte KEY_7 = 36;
        public static byte KEY_8 = 37;
        public static byte KEY_9 = 38;
        public static byte KEY_0 = 39;
        public static byte KEY_ENTER = 40;
        public static byte KEY_ESC = 41;
        public static byte KEY_BACKSPACE = 42;
        public static byte KEY_TAB = 43;
        public static byte KEY_SPACE = 44;
        public static byte KEY_MINUS = 45;
        public static byte KEY_EQUAL = 46;
        public static byte KEY_LEFT_BRACE = 47;
        public static byte KEY_RIGHT_BRACE = 48;
        public static byte KEY_BACKSLASH = 49;
        public static byte KEY_NUMBER = 50;
        public static byte KEY_SEMICOLON = 51;
        public static byte KEY_QUOTE = 52;
        public static byte KEY_TILDE = 53;
        public static byte KEY_COMMA = 54;
        public static byte KEY_PERIOD = 55;
        public static byte KEY_SLASH = 56;
        public static byte KEY_CAPS_LOCK = 57;
        public static byte KEY_F1 = 58;
        public static byte KEY_F2 = 59;
        public static byte KEY_F3 = 60;
        public static byte KEY_F4 = 61;
        public static byte KEY_F5 = 62;
        public static byte KEY_F6 = 63;
        public static byte KEY_F7 = 64;
        public static byte KEY_F8 = 65;
        public static byte KEY_F9 = 66;
        public static byte KEY_F10 = 67;
        public static byte KEY_F11 = 68;
        public static byte KEY_F12 = 69;
        public static byte KEY_PRINTSCREEN = 70;
        public static byte KEY_SCROLL_LOCK = 71;
        public static byte KEY_PAUSE = 72;
        public static byte KEY_INSERT = 73;
        public static byte KEY_HOME = 74;
        public static byte KEY_PAGE_UP = 75;
        public static byte KEY_DELETE = 76;
        public static byte KEY_END = 77;
        public static byte KEY_PAGE_DOWN = 78;
        public static byte KEY_RIGHT = 79;
        public static byte KEY_LEFT = 80;
        public static byte KEY_DOWN = 81;
        public static byte KEY_UP = 82;
        public static byte KEY_NUM_LOCK = 83;
        public static byte KEYPAD_SLASH = 84;
        public static byte KEYPAD_ASTERIX = 85;
        public static byte KEYPAD_MINUS = 86;
        public static byte KEYPAD_PLUS = 87;
        public static byte KEYPAD_ENTER = 88;
        public static byte KEYPAD_1 = 89;
        public static byte KEYPAD_2 = 90;
        public static byte KEYPAD_3 = 91;
        public static byte KEYPAD_4 = 92;
        public static byte KEYPAD_5 = 93;
        public static byte KEYPAD_6 = 94;
        public static byte KEYPAD_7 = 95;
        public static byte KEYPAD_8 = 96;
        public static byte KEYPAD_9 = 97;
        public static byte KEYPAD_0 = 98;
        public static byte KEYPAD_PERIOD = 99;
    }
}
